name: Publish Packages

on:
  push:
    tags:
       - '*'

jobs:
  build:
  
    runs-on: ubuntu-18.04
      
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test
    - name: Pack with dotnet
      run: dotnet pack Mogawinch.TicTacToe.Gameplay/Mogawinch.TicTacToe.Gameplay.csproj --output nuget-packages --configuration Release -p:PackageVersion=$RELEASE_VERSION 
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

